<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <OutputPath>$(RELOADEDIIMODS)/fftivc.utility.modloader</OutputPath>
    <ImplicitUsings>enable</ImplicitUsings>
	<UseWindowsForms>true</UseWindowsForms>
	  
    <!-- IL Trimming Support for Framework Dependent Apps. Unofficial.
         If you set this to true, trimming will be enabled when you publish the mod.
         Test trimming with: `BuildLinked.ps1` in PowerShell. -->
    <ReloadedILLink>false</ReloadedILLink>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <ReloadedLinkRoots Include="fftivc.utility.modloader" />
    <!-- Add assemblies to be trimmed. You might need to add their dependencies too!  -->
    <!-- <ReloadedLinkAssemblies Include="Reloaded.Memory" /> -->
  </ItemGroup>

  <Import Project="Reloaded.Trimming.targets" />
  <Import Project="Reloaded.Checks.targets" />

  <ItemGroup>
    <None Remove="ModConfig.json" />
    <None Remove="Publish.ps1" />
    <None Remove="BuildLinked.ps1" />
    <None Remove="Reloaded.Trimming.targets" />
    <None Remove="Reloaded.Checks.targets" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ModConfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FF16Tools.Files" Version="1.5.0" />
    <PackageReference Include="FF16Tools.Pack" Version="1.2.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.228">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Reloaded.Mod.Interfaces" Version="2.5.0" ExcludeAssets="runtime" />
	<PackageReference Include="Reloaded.Memory" Version="9.4.3" />
	<PackageReference Include="Reloaded.Memory.SigScan.ReloadedII.Interfaces" Version="1.2.0" />
	<PackageReference Include="Reloaded.Mod.Loader.IO" Version="2.5.0" />
    <PackageReference Include="Reloaded.SharedLib.Hooks" Version="1.9.0" />
    <PackageReference Include="YAXLib" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\fftivc.utility.modloader.Interfaces\fftivc.utility.modloader.Interfaces.csproj" />
	  <ProjectReference Include="..\fftivc.utility.modloader.Serializers\fftivc.utility.modloader.Serializers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="FileLists\fftpack.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Preview.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\AbilityActionData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\AbilityChargeAimData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\AbilityTypeData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\AbilityData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\AbilityEffectNumberFilterData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\AbilityJumpData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\AbilityMathData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\AbilityThrowData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\CommandTypeData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\ItemAccessoryData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\ItemArmorData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\ItemCategoryToDataTypeData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\ItemConsumableData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\ItemData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\ItemDataTypeToItemIdRangeData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\ItemEquipBonusData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\ItemIdRangeToCategoryData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\ItemOptionsData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\ItemShieldData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\ItemShopsData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\ItemWeaponData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\JobCommandData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\JobData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\JobNeedLevelData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\MapTrapFormationData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\MonsterJobCommandData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\SpawnData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\SpawnVarianceData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TableData\StatusEffectData.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

	<!-- Get rid of dstorage dlls produced, we run inside the game so we don't need these -->
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<RemoveDir Directories="$(RELOADEDIIMODS)\fftivc.utility.modloader\runtimes">
			<Output TaskParameter="RemovedDirectories" ItemName="DeletedList" />
		</RemoveDir>
		<Message Text="Files deleted: @(DeletedList)" />
		
		<RemoveDir Directories="$(RELOADEDIIMODS)\fftivc.utility.modloader\Nex\Layouts\faith" /> <!-- Only care for ffto layouts -->
	</Target>
</Project>
